apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - name: server
      port: 5000
      targetPort:  5000

---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: study_server:latest 
    command: ["python", "server.py"] 
    imagePullPolicy: Never
    ports:
    - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  containers:
  - name: client
    image: study_client:latest 
    imagePullPolicy: Never
    command: ["python", "client.py"] 
    ports:
    - containerPort: 5000